### ISSUE TITLE
无法自动登录

### ISSUE THREAD

**Issue by bianji1** [GavinIves/XuexiXuexi#1]
启动自动登录并设置密码后，没有自动登录

**Comment by GavinIves** [comment]
> 启动自动登录并设置密码后，没有自动登录

第一次要手动登陆一次 你把你改过的源码发一份我看看

**Comment by bianji1** [comment]
改动有两处
1.os.system("adb shell am broadcast -a ADB_INPUT_TEXT --es msg '这里改成自己的密码'")
2.login()#这里去掉注释

**Comment by bianji1** [comment]
> > 启动自动登录并设置密码后，没有自动登录
> 
> 第一次要手动登陆一次 你把你改过的源码发一份我看看

改动有两处
1.os.system("adb shell am broadcast -a ADB_INPUT_TEXT --es msg '这里改成自己的密码'")
2.login()#这里去掉注释

**Comment by GavinIves** [comment]
没有问题啊 我这里一切正常 报错是什么 密码输入后没有点登录 还是直接没有输密码

**Comment by bianji1** [comment]
> 没有问题啊 我这里一切正常 报错是什么 密码输入后没有点登录 还是直接没有输密码

直接停留在密码输入框那里，应该是直接没有输入密码

**Comment by GavinIves** [comment]
> > 没有问题啊 我这里一切正常 报错是什么 密码输入后没有点登录 还是直接没有输密码
> 
> 直接停留在密码输入框那里，应该是直接没有输入密码

在密码上面有一行代码 是点击密码框的 你的分辨率可能和我不一样 你得改那个点击的位置 让他点击密码输入框

**Comment by bianji1** [comment]
> > > 没有问题啊 我这里一切正常 报错是什么 密码输入后没有点登录 还是直接没有输密码
> > 
> > 
> > 直接停留在密码输入框那里，应该是直接没有输入密码
> 
> 在密码上面有一行代码 是点击密码框的 你的分辨率可能和我不一样 你得改那个点击的位置 让他点击密码输入框

好的，我试一下

**Comment by bianji1** [comment]
按你说的更改后可以正常输入密码了，多谢
